import type { LLDDraft, LLDTemplate, UmlMember, UmlVisibility } from "../types/lld";

function member(id: string, visibility: UmlVisibility, signature: string): UmlMember {
  return { id, signature, visibility };
}

export const lldTemplates: LLDTemplate[] = [
  {
    id: "order-platform",
    name: "Order Platform",
    description: "Services, entities, status enum, and a payment contract.",
    draft: {
      classes: [
        {
          id: "class-order-service",
          kind: "class",
          name: "OrderService",
          position: { x: 120, y: 120 },
          attributes: [
            member("order-service-repo", "-", "orderRepository: OrderRepository"),
            member("order-service-payment", "-", "paymentGateway: PaymentGateway"),
          ],
          methods: [
            member("order-service-create", "+", "createOrder(request: OrderRequest): Order"),
            member("order-service-cancel", "+", "cancelOrder(orderId: string): void"),
          ],
          responsibility: "Coordinates order lifecycle operations and delegates persistence/payment work.",
        },
        {
          id: "class-order",
          kind: "class",
          name: "Order",
          position: { x: 520, y: 120 },
          attributes: [
            member("order-id", "-", "id: string"),
            member("order-status", "-", "status: OrderStatus"),
            member("order-items", "-", "items: OrderItem[]"),
          ],
          methods: [
            member("order-add-item", "+", "addItem(item: OrderItem): void"),
            member("order-mark-paid", "+", "markPaid(): void"),
          ],
          responsibility: "Domain entity that owns order state transitions.",
        },
        {
          id: "interface-payment-gateway",
          kind: "interface",
          name: "PaymentGateway",
          position: { x: 920, y: 140 },
          attributes: [],
          methods: [member("payment-charge", "+", "charge(amount: Money): PaymentResult")],
          responsibility: "Boundary for payment provider integrations.",
        },
        {
          id: "enum-order-status",
          kind: "enum",
          name: "OrderStatus",
          position: { x: 530, y: 420 },
          attributes: [
            member("order-status-created", "+", "CREATED"),
            member("order-status-paid", "+", "PAID"),
            member("order-status-cancelled", "+", "CANCELLED"),
          ],
          methods: [],
          responsibility: "Defines valid order lifecycle states.",
        },
      ],
      relationships: [
        {
          id: "relationship-service-order",
          sourceClassId: "class-order-service",
          targetClassId: "class-order",
          kind: "association",
          label: "creates",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "relationship-service-payment",
          sourceClassId: "class-order-service",
          targetClassId: "interface-payment-gateway",
          kind: "dependency",
          label: "uses",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
        {
          id: "relationship-order-status",
          sourceClassId: "class-order",
          targetClassId: "enum-order-status",
          kind: "composition",
          label: "has status",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
      ],
    },
  },
  {
    id: "parking-lot",
    name: "Parking Lot",
    description: "Vehicles, spots, tickets, gates, and pricing strategy.",
    draft: {
      classes: [
        {
          id: "class-parking-lot",
          kind: "class",
          name: "ParkingLot",
          position: { x: 100, y: 120 },
          attributes: [
            member("parking-lot-id", "-", "id: string"),
            member("parking-lot-floors", "-", "floors: ParkingFloor[]"),
          ],
          methods: [
            member("parking-lot-park", "+", "park(vehicle: Vehicle): ParkingTicket"),
            member("parking-lot-exit", "+", "exit(ticketId: string): Receipt"),
          ],
          responsibility: "Facade that coordinates spot assignment, ticketing, and payment at the lot level.",
        },
        {
          id: "class-parking-floor",
          kind: "class",
          name: "ParkingFloor",
          position: { x: 500, y: 80 },
          attributes: [member("parking-floor-spots", "-", "spots: ParkingSpot[]")],
          methods: [member("parking-floor-find", "+", "findAvailableSpot(type: VehicleType): ParkingSpot")],
          responsibility: "Owns spot availability for one floor.",
        },
        {
          id: "class-parking-spot",
          kind: "class",
          name: "ParkingSpot",
          position: { x: 900, y: 80 },
          attributes: [
            member("parking-spot-id", "-", "id: string"),
            member("parking-spot-type", "-", "type: VehicleType"),
            member("parking-spot-occupied", "-", "occupied: boolean"),
          ],
          methods: [
            member("parking-spot-assign", "+", "assign(vehicle: Vehicle): void"),
            member("parking-spot-release", "+", "release(): void"),
          ],
          responsibility: "Represents occupancy and vehicle compatibility for one physical spot.",
        },
        {
          id: "abstract-vehicle",
          kind: "abstract",
          name: "Vehicle",
          position: { x: 900, y: 390 },
          attributes: [
            member("vehicle-plate", "#", "licensePlate: string"),
            member("vehicle-type", "#", "type: VehicleType"),
          ],
          methods: [member("vehicle-get-type", "+", "getType(): VehicleType")],
          responsibility: "Base abstraction for parkable vehicles.",
        },
        {
          id: "class-parking-ticket",
          kind: "class",
          name: "ParkingTicket",
          position: { x: 500, y: 390 },
          attributes: [
            member("ticket-id", "-", "id: string"),
            member("ticket-entry", "-", "entryTime: Date"),
            member("ticket-spot", "-", "spotId: string"),
          ],
          methods: [member("ticket-close", "+", "close(exitTime: Date): void")],
          responsibility: "Tracks an active parking session.",
        },
        {
          id: "interface-pricing-strategy",
          kind: "interface",
          name: "PricingStrategy",
          position: { x: 100, y: 430 },
          attributes: [],
          methods: [member("pricing-calc", "+", "calculate(ticket: ParkingTicket): Money")],
          responsibility: "Contract for fee calculation rules.",
        },
      ],
      relationships: [
        {
          id: "rel-lot-floor",
          sourceClassId: "class-parking-lot",
          targetClassId: "class-parking-floor",
          kind: "composition",
          label: "contains",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "rel-floor-spot",
          sourceClassId: "class-parking-floor",
          targetClassId: "class-parking-spot",
          kind: "composition",
          label: "contains",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "rel-ticket-spot",
          sourceClassId: "class-parking-ticket",
          targetClassId: "class-parking-spot",
          kind: "association",
          label: "reserves",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
        {
          id: "rel-lot-pricing",
          sourceClassId: "class-parking-lot",
          targetClassId: "interface-pricing-strategy",
          kind: "dependency",
          label: "uses",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
        {
          id: "rel-spot-vehicle",
          sourceClassId: "class-parking-spot",
          targetClassId: "abstract-vehicle",
          kind: "association",
          label: "parks",
          sourceMultiplicity: "1",
          targetMultiplicity: "0..1",
        },
      ],
    },
  },
  {
    id: "splitwise",
    name: "Splitwise",
    description: "Users, groups, expenses, splits, and settlement strategy.",
    draft: {
      classes: [
        {
          id: "class-expense-service",
          kind: "class",
          name: "ExpenseService",
          position: { x: 80, y: 130 },
          attributes: [
            member("expense-service-repo", "-", "expenseRepository: ExpenseRepository"),
            member("expense-service-settlement", "-", "settlementStrategy: SettlementStrategy"),
          ],
          methods: [
            member("expense-add", "+", "addExpense(request: ExpenseRequest): Expense"),
            member("expense-balance", "+", "getBalances(groupId: string): BalanceSheet"),
          ],
          responsibility: "Coordinates expense creation and balance calculation.",
        },
        {
          id: "class-group",
          kind: "class",
          name: "Group",
          position: { x: 480, y: 80 },
          attributes: [
            member("group-id", "-", "id: string"),
            member("group-members", "-", "members: User[]"),
          ],
          methods: [member("group-add-member", "+", "addMember(user: User): void")],
          responsibility: "Owns members and shared expenses for a circle.",
        },
        {
          id: "class-expense",
          kind: "class",
          name: "Expense",
          position: { x: 860, y: 90 },
          attributes: [
            member("expense-id", "-", "id: string"),
            member("expense-paid-by", "-", "paidBy: User"),
            member("expense-splits", "-", "splits: Split[]"),
          ],
          methods: [member("expense-validate", "+", "validateSplits(): boolean")],
          responsibility: "Represents one spending event and its split allocation.",
        },
        {
          id: "class-split",
          kind: "class",
          name: "Split",
          position: { x: 860, y: 390 },
          attributes: [
            member("split-user", "-", "user: User"),
            member("split-amount", "-", "amount: Money"),
          ],
          methods: [member("split-update", "+", "updateAmount(amount: Money): void")],
          responsibility: "Represents one participant share of an expense.",
        },
        {
          id: "class-user",
          kind: "class",
          name: "User",
          position: { x: 480, y: 410 },
          attributes: [
            member("user-id", "-", "id: string"),
            member("user-name", "-", "name: string"),
          ],
          methods: [member("user-display", "+", "displayName(): string")],
          responsibility: "Identifies a participant in groups and expenses.",
        },
        {
          id: "interface-settlement-strategy",
          kind: "interface",
          name: "SettlementStrategy",
          position: { x: 80, y: 440 },
          attributes: [],
          methods: [member("settlement-simplify", "+", "simplify(balances: BalanceSheet): Settlement[]")],
          responsibility: "Contract for simplifying debts between users.",
        },
      ],
      relationships: [
        {
          id: "rel-service-expense",
          sourceClassId: "class-expense-service",
          targetClassId: "class-expense",
          kind: "association",
          label: "creates",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "rel-service-strategy",
          sourceClassId: "class-expense-service",
          targetClassId: "interface-settlement-strategy",
          kind: "dependency",
          label: "uses",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
        {
          id: "rel-group-user",
          sourceClassId: "class-group",
          targetClassId: "class-user",
          kind: "aggregation",
          label: "has members",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "rel-expense-split",
          sourceClassId: "class-expense",
          targetClassId: "class-split",
          kind: "composition",
          label: "has splits",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "rel-split-user",
          sourceClassId: "class-split",
          targetClassId: "class-user",
          kind: "association",
          label: "for",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
      ],
    },
  },
  {
    id: "elevator-system",
    name: "Elevator System",
    description: "Controllers, elevators, requests, scheduling, and state.",
    draft: {
      classes: [
        {
          id: "class-elevator-controller",
          kind: "class",
          name: "ElevatorController",
          position: { x: 80, y: 130 },
          attributes: [
            member("controller-elevators", "-", "elevators: Elevator[]"),
            member("controller-scheduler", "-", "scheduler: SchedulingStrategy"),
          ],
          methods: [
            member("controller-submit", "+", "submit(request: ElevatorRequest): void"),
            member("controller-dispatch", "+", "dispatch(): void"),
          ],
          responsibility: "Accepts requests and coordinates elevator assignment.",
        },
        {
          id: "class-elevator",
          kind: "class",
          name: "Elevator",
          position: { x: 500, y: 120 },
          attributes: [
            member("elevator-id", "-", "id: string"),
            member("elevator-floor", "-", "currentFloor: number"),
            member("elevator-state", "-", "state: ElevatorState"),
          ],
          methods: [
            member("elevator-move", "+", "moveTo(floor: number): void"),
            member("elevator-open", "+", "openDoor(): void"),
          ],
          responsibility: "Owns movement and door operations for one car.",
        },
        {
          id: "class-request",
          kind: "class",
          name: "ElevatorRequest",
          position: { x: 900, y: 130 },
          attributes: [
            member("request-source", "-", "sourceFloor: number"),
            member("request-target", "-", "targetFloor: number"),
            member("request-direction", "-", "direction: Direction"),
          ],
          methods: [member("request-is-up", "+", "isUp(): boolean")],
          responsibility: "Captures a floor/car request to be scheduled.",
        },
        {
          id: "interface-scheduling",
          kind: "interface",
          name: "SchedulingStrategy",
          position: { x: 80, y: 440 },
          attributes: [],
          methods: [member("scheduling-select", "+", "selectElevator(request: ElevatorRequest): Elevator")],
          responsibility: "Contract for choosing the best elevator for a request.",
        },
        {
          id: "enum-elevator-state",
          kind: "enum",
          name: "ElevatorState",
          position: { x: 500, y: 430 },
          attributes: [
            member("state-idle", "+", "IDLE"),
            member("state-moving", "+", "MOVING"),
            member("state-maintenance", "+", "MAINTENANCE"),
          ],
          methods: [],
          responsibility: "Defines lifecycle states for an elevator car.",
        },
      ],
      relationships: [
        {
          id: "rel-controller-elevator",
          sourceClassId: "class-elevator-controller",
          targetClassId: "class-elevator",
          kind: "aggregation",
          label: "manages",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "rel-controller-scheduler",
          sourceClassId: "class-elevator-controller",
          targetClassId: "interface-scheduling",
          kind: "dependency",
          label: "uses",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
        {
          id: "rel-controller-request",
          sourceClassId: "class-elevator-controller",
          targetClassId: "class-request",
          kind: "association",
          label: "handles",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "rel-elevator-state",
          sourceClassId: "class-elevator",
          targetClassId: "enum-elevator-state",
          kind: "composition",
          label: "has state",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
      ],
    },
  },
  {
    id: "food-delivery",
    name: "Food Delivery",
    description: "Orders, restaurants, menus, delivery assignment, and payment.",
    draft: {
      classes: [
        {
          id: "class-delivery-order-service",
          kind: "class",
          name: "OrderService",
          position: { x: 80, y: 130 },
          attributes: [
            member("delivery-order-repo", "-", "orderRepository: OrderRepository"),
            member("delivery-payment", "-", "paymentGateway: PaymentGateway"),
          ],
          methods: [
            member("delivery-place-order", "+", "placeOrder(request: OrderRequest): Order"),
            member("delivery-assign", "+", "assignPartner(orderId: string): DeliveryAssignment"),
          ],
          responsibility: "Coordinates checkout, payment, and delivery assignment.",
        },
        {
          id: "class-restaurant",
          kind: "class",
          name: "Restaurant",
          position: { x: 500, y: 80 },
          attributes: [
            member("restaurant-id", "-", "id: string"),
            member("restaurant-menu", "-", "menu: Menu"),
          ],
          methods: [member("restaurant-accept", "+", "accept(order: Order): void")],
          responsibility: "Owns menu and restaurant-side order acceptance.",
        },
        {
          id: "class-menu",
          kind: "class",
          name: "Menu",
          position: { x: 900, y: 80 },
          attributes: [member("menu-items", "-", "items: MenuItem[]")],
          methods: [member("menu-find", "+", "findItem(itemId: string): MenuItem")],
          responsibility: "Collection of sellable items for a restaurant.",
        },
        {
          id: "class-delivery-order",
          kind: "class",
          name: "Order",
          position: { x: 500, y: 400 },
          attributes: [
            member("delivery-order-id", "-", "id: string"),
            member("delivery-order-status", "-", "status: OrderStatus"),
            member("delivery-order-items", "-", "items: OrderItem[]"),
          ],
          methods: [member("delivery-order-total", "+", "calculateTotal(): Money")],
          responsibility: "Owns customer order state and line items.",
        },
        {
          id: "class-delivery-partner",
          kind: "class",
          name: "DeliveryPartner",
          position: { x: 900, y: 400 },
          attributes: [
            member("partner-id", "-", "id: string"),
            member("partner-available", "-", "available: boolean"),
          ],
          methods: [member("partner-assign", "+", "assign(order: Order): void")],
          responsibility: "Represents a courier who can fulfill delivery.",
        },
        {
          id: "interface-delivery-payment",
          kind: "interface",
          name: "PaymentGateway",
          position: { x: 80, y: 450 },
          attributes: [],
          methods: [member("delivery-payment-charge", "+", "charge(order: Order): PaymentResult")],
          responsibility: "Boundary for online payment providers.",
        },
      ],
      relationships: [
        {
          id: "rel-delivery-service-order",
          sourceClassId: "class-delivery-order-service",
          targetClassId: "class-delivery-order",
          kind: "association",
          label: "creates",
          sourceMultiplicity: "1",
          targetMultiplicity: "*",
        },
        {
          id: "rel-delivery-service-payment",
          sourceClassId: "class-delivery-order-service",
          targetClassId: "interface-delivery-payment",
          kind: "dependency",
          label: "uses",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
        {
          id: "rel-restaurant-menu",
          sourceClassId: "class-restaurant",
          targetClassId: "class-menu",
          kind: "composition",
          label: "owns",
          sourceMultiplicity: "1",
          targetMultiplicity: "1",
        },
        {
          id: "rel-order-restaurant",
          sourceClassId: "class-delivery-order",
          targetClassId: "class-restaurant",
          kind: "association",
          label: "from",
          sourceMultiplicity: "*",
          targetMultiplicity: "1",
        },
        {
          id: "rel-order-partner",
          sourceClassId: "class-delivery-order",
          targetClassId: "class-delivery-partner",
          kind: "association",
          label: "assigned to",
          sourceMultiplicity: "*",
          targetMultiplicity: "0..1",
        },
      ],
    },
  },
];

export function cloneLLDDraft(draft: LLDDraft): LLDDraft {
  return {
    classes: draft.classes.map((umlClass) => ({
      ...umlClass,
      attributes: umlClass.attributes.map((attribute) => ({ ...attribute })),
      methods: umlClass.methods.map((method) => ({ ...method })),
      position: { ...umlClass.position },
    })),
    relationships: draft.relationships.map((relationship) => ({ ...relationship })),
  };
}

export function getDefaultLLDDraft(): LLDDraft {
  return cloneLLDDraft(lldTemplates[0].draft);
}
